Authorization_failed_error_code: 3013
Authorization_failed_error: Authorisation Failed
Authorization_failed_reason: Authorisation Failed

Token_not_provided_error_code : 3015
Token_not_provided_error : Token ID is required in the header
Token_not_provided_reason : Token not provided

Token_invalid_error_code : 3016
Token_invalid_error : Token ID provided is Invalid
Token_invalid_reason : Token Invalid

Token_expire_error_code : 3017
Token_expire_error : Token ID provided is expired
Token_expire_reason : Token Expired

User_not_exist_error_code : 3018
User_not_exist_error : User not exists
User_not_exist_reason : User not exists


Retry_limit_exceed_error_code: 3019
Retry_limit_exceed_error: Retry limit exceeded
Retry_limit_exceed_reason: Retry limit exceeded

Header_missing_error_code : 3001
Header_missing_error :  is required in the request header
Header_missing_reason : One or more parameter(s) required is missing in the header


Header_invalid_error_code : 3002
Header_invalid_error : Invalid {0} value provided in the request header
Header_invalid_reason : One or more parameter(s) is invalid in the header

Logout_failed_error_code: 3020
Logout_failed_error: Logout Failed





//TODO: remove these properties after code review
One_or_more_parameters_required_is_missing_in_the_header_error_code: 3001
One_or_more_parameters_is_invalid_in_the_header_error_code: 3002
Required_parameter_is_missing_in_the_URL_error_code: 3003
Invalid_parameter_value_sent_in_the_URL_error_code: 3004
One_or_more_required_parameter_is_missing_in_the_request_body_error_code: 1005
Invalid_parameter_value_sent_in_request_error_code: 3006
Something_you_looking_for_does_not_exist_error_code: 3007
Unable_to_connect_to_resource_error_code: 3008
Unable_to_connect_to_Rules_Engine_error_code: 3009
Error_received_from_Third_party_source_error_code: 3010
Error_response_received_from_Rules_Engine_error_code: 3011
Rules_not_configured_for_the_request_sent_error_code: 3012
Authorisation_Failed_error_code: 3013
No_results_found_for_requested_parameter_Filters_error_code: 3014
Token_invalid_or_expired_error_code: 3016
One_or_more_parameters_required_is_missing_in_the_header_error_message:  is required in the request header
One_or_more_parameters_is_invalid_in_the_header_error_message: Invalid {0} value provided in the request header
Required_parameter_is_missing_in_the_URL_error_message:  is required in the URL parameter
Invalid_parameter_value_sent_in_the_URL_error_message: Invalid {0} value provided in the URL
One_or_more_required_parameter_is_missing_in_the_request_body_error_message:  is required in the request
Invalid_parameter_value_sent_in_request_error_message: Invalid {0} value provided in the request
Something_you_looking_for_does_not_exist_error_message:  does not exists in our records or is not eligible for the request
Unable_to_connect_to_resource_error_message: Unable to connect to one or more resources
Unable_to_connect_to_Rules_Engine_error_message: Unable to connect to one or more resources
Error_received_from_Third_party_source_error_message: Error occurred while processing request {0}
Error_response_received_from_Rules_Engine_error_message: Error occurred while fetching one or more resources
Rules_not_configured_for_the_request_sent_error_message: Error occurred while fetching one of more resources
Authorisation_Failed_error_message: Authorisation Failed
No_results_found_for_requested_parameter_Filters_error_message: No results found for the requested parameters
Token_not_provided_error_message: Token ID is required in the header
Token_invalid_or_expired_error_message: Token ID provided is either Invalid or has expired










