server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


gce:
  tenant-realm-mapping:
    1: rbs
    2: natwest
    3: ulster-ri
    4: ulster-ni

oauth2:
  client-id: ng-auth
  client-secret: 3466c537-6b12-4ecf-b713-60ae82317d5e
  auth-server-base-url: http://localhost:8080/auth