server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admin@123$
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


gce:
  tenant-realm-mapping:
    1: master
    2: natwest
    3: ulster-ri
    4: ulster-ni

oauth2:
  client-id: szells-server
  client-secret: cef2c6e8-8ed6-4932-84b2-8789c176a9c3
  auth-server-base-url: http://ec2-18-191-199-237.us-east-2.compute.amazonaws.com:8080/auth

member-fetch-token: http://localhost:9001/core/client/fetchToken