package com.dxunited.core.auth.mail;

public interface IWelcomeTemplate {

    static String emailContent(String member_name, String reset_code) {

        String reset_link = "http://ec2-18-219-247-17.us-east-2.compute.amazonaws.com:9080/reset-password/" + reset_code;
        return "<!DOCTYPE html>\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "<head>\n"
                + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n"
                + "<!--[if !mso]><!-->\n"
                + "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
                + "<!--<![endif]-->\n"
                + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
                + "<title>Shoppie | Activation Completed</title>\n"
                + "<link rel=\"stylesheet\" href=\"http://szells.com.s3-website.us-east-2.amazonaws.com/styles/bootstrap.css\">\n"
                + "<link rel=\"stylesheet\" href=\"http://szells.com.s3-website.us-east-2.amazonaws.com/styles/web.css\">\n"
                + "<link rel=\"stylesheet\" href=\"http://szells.com.s3-website.us-east-2.amazonaws.com/styles/style.css\">\n"
                + "<link rel=\"stylesheet\" href=\"http://szells.com.s3-website.us-east-2.amazonaws.com/styles/responsive.css\">\n"
                + "<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\" >\n"
                + "<style type=\"text/css\">\n"
                + "body, html {\n"
                + "-webkit-text-size-adjust: 100%;\n"
                + "-ms-text-size-adjust: 100%;\n"
                + "margin: 0;\n"
                + "height: 100%;\n"
                + "}\n"
                + "bg {\n"
                + "background-image: url(\"http://szells.com.s3-website.us-east-2.amazonaws.com/img/back2.png\");\n"
                + "height: 100%;\n"
                + "background-position: center;\n"
                + "background-repeat: no-repeat;\n"
                + "background-size: cover;\n"
                + "}\n"
                + "</style>\n"
                + "</head>\n"
                + "\n"
                + "<body className=\"bg\" topmargin=\"0\" rightmargin=\"0\" bottommargin=\"0\" leftmargin=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" style=\"border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; width: 100%; height: 100%; -webkit-font-smoothing: antialiased; text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; line-height: 100%;  background-color: #D8D8D8; color: #000000;\" bgcolor=\"#FFFFFF\" text=\"#000000\">\n"
                + "<div className=\"height: 100vh !important;width: 100vw !important; margin: 0px;  \">\n"
                + "<table bgcolor=\"#ffffff\" width=\"700\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" className=\"devicewidth\">\n"
                + "<tr style=\"background: #20b3e5;height: 100%  !important; \">\n"
                + "<td align=\"center\" valign=\"top\" style=\"border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 2.25%; padding-right: 6.25%; width: 87.5%; padding-top: 18px;padding-bottom: 23px; \">\n"
                + "<img border=\"0\" vspace=\"0\" hspace=\"0\" src=\"http://szells.com.s3-website.us-east-2.amazonaws.com/img/logo_11.png\" width=\"220\" height=\"auto\" alt=\"Logo\" title=\"Logo\" style=\"float: left; color: #000000; font-size: 10px; margin: 0; padding: 0; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; border: none; display: block;\"/>\n"
                + "</td>\n"
                + "</tr>\n"
                + "<tr>\n"
                + "<td align=\"center\" valign=\"top\" style=\"border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 5.25%; padding-right: 3.25%; width: 87.5%; font-size: 17px; font-weight: 400; line-height: 28px; padding-top:70px; padding-bottom:70px; color: #262626; font-family: Bw Glenn Sans; text-align:left\" className=\"paragraph\">\n"
                + "<p style=\"margin-bottom: 0 !important;font-size: 20px;margin-bottom: 11px !important;\">Hi <strong>" + member_name + "</strong></p>\n"
                + "<p style=\"margin: 0 !important;font-size: 20px;margin-bottom: 11px !important;\">You recently requested to reset your password for your <strong>\"Customer Loyalty account\"</strong>.</p>\n"
                + "<p style=\"margin: 0 !important;font-size: 20px;margin-bottom: 11px !important;\">Please <a href=" + reset_link + " style=\"text-decoration: none;color: #17e0e2;font-weight: bold;\">click here</a> to reset it. The password reset is only valid for the next 1 hour.</p>\n"
                + "<p style=\"margin: 0 !important;font-size: 20px;margin-bottom: 11px !important;\">You could also copy the below link and paste in your browser address bar</p>\n"
                + "<p style=\"margin: 0 !important;font-size: 20px;margin-bottom: 50px !important;margin-top: 50px !important;\"><a href=" + reset_link + " style=\"text-decoration: none;color: #17e0e2;font-weight: bold;\">http://ec2-18-219-247-17.us-east-2.compute.amazonaws.com:9080/login</a></p>\n"
                + "<p style=\"margin: 0 !important;font-size: 20px;margin-bottom: 50px !important;\">If you did not request a password reset, please ignore this email. </p>\n"
                + "<p style=\"margin: 0 !important;font-size: 20px;margin-bottom: 11px !important;\">Thanks,</p>\n"
                + "<p style=\"margin: 0 !important;font-size: 20px;margin-bottom: 11px !important;\">Szells Team</p>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</div>\n"
                + "</body>\n"
                + "</html>\n";
    }
}

