CREATE SEQUENCE IF NOT EXISTS GCE.HIBERNATE_SEQUENCE START 1;

CREATE TABLE GCE.LOGIN_FAILURE_ATTEMPT
(
    ATTEMPT_ID    BIGINT       NOT NULL PRIMARY KEY,
    TENANT_ID     VARCHAR(100) NOT NULL,
    MEMBER_ID     VARCHAR(100) NOT NULL,
    FAIL_COUNT    SMALLINT     NOT NULL,
    DATE_CREATED  TIMESTAMP    NOT NULL,
    DATE_MODIFIED TIMESTAMP    NULL
);
